In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import cross_val_score
from sklearn import ensemble
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error
from sklearn import datasets
from sklearn.utils import shuffle

/Users/samuelkim/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


We will use the 2014 NYC Crime dataset we have used in previous exercises. 

In [2]:
excel_file='Table_8_Offenses_Known_to_Law_Enforcement_by_New_York_by_City_2014.xls'
df=pd.read_excel(excel_file)
df.head()

Table 8  Unnamed: 1      Unnamed: 2  \
0                           NEW YORK         NaN             NaN   
1  Offenses Known to Law Enforcement         NaN             NaN   
2                      by City, 2014         NaN             NaN   
3                               City  Population  Violent\ncrime   
4                      Adams Village        1851               0   

                               Unnamed: 3                    Unnamed: 4  \
0                                     NaN                           NaN   
1                                     NaN                           NaN   
2                                     NaN                           NaN   
3  Murder and\nnonnegligent\nmanslaughter  Rape\n(revised\ndefinition)1   
4                                       0                           NaN   

                    Unnamed: 5 Unnamed: 6           Unnamed: 7  \
0                          NaN        NaN                  NaN   
1                                     NaN                  NaN   
2                          NaN        NaN                  NaN   
3  Rape\n(legacy\ndefinition)2    Robbery  Aggravated\nassault   
4                            0          0                    0   

        Unnamed: 8 Unnamed: 9      Unnamed: 10            Unnamed: 11  \
0              NaN        NaN              NaN                    NaN   
1              NaN        NaN              NaN                    NaN   
2              NaN        NaN              NaN                    NaN   
3  Property\ncrime   Burglary  Larceny-\ntheft  Motor\nvehicle\ntheft   
4               11          1               10                      0   

  Unnamed: 12  
0         NaN  
1         NaN  
2         NaN  
3      Arson3  
4           0

In [3]:
columns=['City','Population','Violent Crime','Murder/Manslaughter','Rape','Rape Legacy','Robbery','Agg Assault',
           'Property Crime','Burgulary','Larceny','Motor_Vehicle Theft','Arson']

df.columns=columns
df[columns]=df[columns].replace(',', '', regex=True)
df.drop(df.head(4).index, inplace=True)
df_new=df.drop(['Rape', 'Arson'], axis=1)
df_new.head()

City Population Violent Crime Murder/Manslaughter  \
4             Adams Village       1851             0                   0   
5  Addison Town and Village       2568             2                   0   
6            Afton Village4        820             0                   0   
7             Akron Village       2842             1                   0   
8                   Albany4      98595           802                   8   

  Rape Legacy Robbery Agg Assault Property Crime Burgulary Larceny  \
4           0       0           0             11         1      10   
5           0       1           1             49         1      47   
6         NaN       0           0              1         0       1   
7           0       0           1             17         0      17   
8         NaN     237         503           3888       683    3083   

  Motor_Vehicle Theft  
4                   0  
5                   1  
6                   0  
7                   0  
8                 122

In [4]:
df_new['Population^2']=df_new['Population'].apply(float)**2
df_new['Murder_new']=np.where(df_new['Murder/Manslaughter'] > 0, 1, 0)
df_new['Robbery_new']=np.where(df_new['Robbery'].apply(float) > 0, 1, 0)
df_new.head()

City Population Violent Crime Murder/Manslaughter  \
4             Adams Village       1851             0                   0   
5  Addison Town and Village       2568             2                   0   
6            Afton Village4        820             0                   0   
7             Akron Village       2842             1                   0   
8                   Albany4      98595           802                   8   

  Rape Legacy Robbery Agg Assault Property Crime Burgulary Larceny  \
4           0       0           0             11         1      10   
5           0       1           1             49         1      47   
6         NaN       0           0              1         0       1   
7           0       0           1             17         0      17   
8         NaN     237         503           3888       683    3083   

  Motor_Vehicle Theft  Population^2  Murder_new  Robbery_new  
4                   0  3.426201e+06           0            0  
5                   1  6.594624e+06           0            1  
6                   0  6.724000e+05           0            0  
7                   0  8.076964e+06           0            0  
8                 122  9.720974e+09           1            1

In [5]:
#If a neighborhood has had a Murder and/or Robbery in 2014, we created a new column "Attn" to point this out. 
#53.2% of neighborhoods have had a murder and/or robbery taking place in the past year.
df_new['Attention'] = np.where(df_new['Murder_new']+df_new['Robbery_new'] >=1, 1, 0)
print('Trouble Neighborhoods:', df_new['Attention'].mean())
df_new.tail()

Trouble Neighborhoods: 0.5319148936170213


City Population  \
375  3 The FBI does not publish arson data unless i...        NaN   
376  4 This agency began the year submitting rape d...        NaN   
377  5 The FBI determined that the agency's data we...        NaN   
378                                                NaN        NaN   
379                                                           NaN   

    Violent Crime Murder/Manslaughter Rape Legacy Robbery Agg Assault  \
375           NaN                 NaN         NaN     NaN         NaN   
376           NaN                 NaN         NaN     NaN         NaN   
377           NaN                 NaN         NaN     NaN         NaN   
378           NaN                 NaN         NaN     NaN         NaN   
379           NaN                 NaN         NaN     NaN         NaN   

    Property Crime Burgulary Larceny Motor_Vehicle Theft  Population^2  \
375            NaN       NaN     NaN                 NaN           NaN   
376            NaN       NaN     NaN                 NaN           NaN   
377            NaN       NaN     NaN                 NaN           NaN   
378            NaN       NaN     NaN                 NaN           NaN   
379            NaN       NaN     NaN                 NaN           NaN   

     Murder_new  Robbery_new  Attention  
375           0            0          0  
376           0            0          0  
377           0            0          0  
378           0            0          0  
379           0            0          0

In [6]:
df_new.replace([np.inf,-np.inf],np.nan)
df_new.dropna(how='any') 

City Population Violent Crime Murder/Manslaughter  \
4                 Adams Village       1851             0                   0   
5      Addison Town and Village       2568             2                   0   
7                 Akron Village       2842             1                   0   
15           Amityville Village       9509            12                   0   
16                    Amsterdam      18099            27                   0   
18               Arcade Village       2030             0                   0   
19              Ardsley Village       4561             1                   0   
20            Asharoken Village        656             0                   0   
21               Attica Village       2502             0                   0   
31                  Black River       1392             0                   0   
33                  Bolton Town       2321             0                   0   
34            Boonville Village       2053             1                   0   
35                   Brant Town       2063             1                   0   
36                     Brewster       2349             0                   0   
37     Briarcliff Manor Village       8060             2                   0   
40           Bronxville Village       6421             2                   0   
41           Brownville Village       1162             0                   0   
45               Camden Village       2214             2                   0   
46    Camillus Town and Village      24307            13                   0   
47          Canajoharie Village       2168             1                   0   
50             Canisteo Village       2236             1                   0   
53                 Carroll Town       3461             4                   0   
55          Cattaraugus Village        975             1                   0   
58       Central Square Village       1839             4                   0   
60              Chatham Village       1721             0                   0   
69           Cobleskill Village       4488             0                   0   
70                Coeymans Town       7441            20                   1   
75   Cornwall-on-Hudson Village       2964             2                   0   
83                  Dewitt Town      22682            20                   0   
84               Dexter Village       1114             0                   0   
..                          ...        ...           ...                 ...   
288    Rockville Centre Village      24127            17                   0   
291              Rotterdam Town      29340            13                   1   
292        Rouses Point Village       2186             0                   0   
294           Rye Brook Village       9544             2                   0   
296          Sag Harbor Village       2275             0                   0   
298         Sands Point Village       2727             0                   0   
301             Saugerties Town      19227            11                   0   
302           Scarsdale Village      17710             1                   0   
305           Schoharie Village        857             0                   0   
312         Shortsville Village       1429             0                   0   
314         Skaneateles Village       2453             1                   0   
315       Sleepy Hollow Village      10051             8                   0   
318              Solvay Village       6467            19                   0   
320         Southampton Village       3158             2                   0   
325             Stillwater Town       6604             0                   0   
327              Stockport Town       2744             0                   0   
329             Suffern Village      10975             5                   1   
331           Tarrytown Village      11531             6                   0   
335                        

In [7]:
X = df_new[['Population', 'Agg Assault', 'Rape Legacy', 'Property Crime', 'Murder_new', 'Robbery_new', 'Attention']].copy().dropna()
data = X.Attention
Y = data

In [8]:
Y.shape

(142,)

In [9]:
X.shape

(142, 7)

# Our Neural Network

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
# Establish and fit with single, 100 perceptron layer 
mlp = MLPClassifier(hidden_layer_sizes=(100,))
mlp.fit(X,Y)
# Cross validate and get scores
cross_val_score(mlp, X, Y, cv=5)

array([0.55172414, 0.44827586, 0.42857143, 0.42857143, 0.57142857])

In [11]:
mlp = MLPClassifier(hidden_layer_sizes=(1000,))
mlp.fit(X,Y)
# Cross validate and get scores
cross_val_score(mlp, X, Y, cv=5)

array([0.44827586, 0.44827586, 0.42857143, 0.42857143, 0.42857143])

In [12]:
mlp = MLPClassifier(hidden_layer_sizes=(100, 100))
mlp.fit(X,Y)
# Cross validate and get scores
cross_val_score(mlp, X, Y, cv=5)

array([0.44827586, 0.44827586, 0.42857143, 0.42857143, 0.42857143])

In [13]:
mlp = MLPClassifier(
    hidden_layer_sizes=(100,),
    activation='tanh',
    alpha=10, 
    learning_rate='adaptive'
)
mlp.fit(X,Y)

# Cross validate and get scores
cross_val_score(mlp, X, Y, cv=5)

array([0.55172414, 0.5862069 , 0.57142857, 0.57142857, 0.57142857])

In [14]:
mlp = MLPClassifier(
    hidden_layer_sizes=(1000,),
    activation='tanh',
    alpha=10, 
    learning_rate='adaptive'
)
mlp.fit(X,Y)

# Cross validate and get scores
cross_val_score(mlp, X, Y, cv=5)

array([0.5862069 , 0.72413793, 0.57142857, 0.57142857, 0.60714286])

In [15]:
mlp = MLPClassifier(
    hidden_layer_sizes=(100,100),
    activation='tanh',
    alpha=10, 
    learning_rate='adaptive'
)
mlp.fit(X,Y)

# Cross validate and get scores
cross_val_score(mlp, X, Y, cv=5)

/Users/samuelkim/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/samuelkim/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/samuelkim/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


array([0.79310345, 0.72413793, 0.71428571, 0.64285714, 0.78571429])

After working with MLP parameters, the double 100 perceptron layers performed the best with an average score of 0.711  although consistency could be improved. We will now compare the neural network's performance with a random forest.


# Random Forest Comparison

In [16]:
forest = ensemble.RandomForestClassifier(
    max_features='sqrt',
)
max_depth = dict(max_depth = np.arange(1,10,1))
grid = GridSearchCV(forest, max_depth, cv=5)
grid.fit(X, Y).best_estimator_.get_params()['max_depth']

1

In [17]:
forest = ensemble.RandomForestClassifier(
    max_features='sqrt',
    max_depth=1
)

cross_val_score(forest, X, Y, cv=5)

array([1.        , 1.        , 1.        , 1.        , 0.96428571])

In [18]:
forest.fit(X,Y)

forest_features = pd.DataFrame()
forest_features['Importance'] = forest.feature_importances_
forest_features['Feature'] = X.columns

forest_features.sort_values('Importance', ascending=False).head(3)
#Two of three most important features in the forest are Attention and Murder_new, newly created features for the challenge

Importance      Feature
6         0.3    Attention
0         0.2   Population
5         0.2  Robbery_new

# Observations

Juxtaposing neural network and random forest, we notice that with the right parameters, they both showed consistency across five folds. However, our RF was clearly overfitting, whereas our neural network was not. We were able to ascertain important features that were considered for RF, but not for NN. The two models varied in speed but that was negligible in this case. 